version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - npm install
      - ng build
  post_build:
    commands:
      - echo Build completed on `date`
      -
artifacts:
  files:
    - *.json
    
  name: webapp-angular
